# Generated by Django 3.2 on 2022-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
