# Generated by Django 3.2 on 2022-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notes_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_for_yourself',
            field=models.TextField(),
        ),
    ]
