# Generated by Django 3.2 on 2022-03-23 18:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_notes_notes_for_yourself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='code_here',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
