# Generated by Django 3.0.4 on 2022-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220324_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='assembly',
            field=models.CharField(max_length=50),
        ),
    ]
