# Generated by Django 3.0.4 on 2022-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220324_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
