# Generated by Django 3.0.4 on 2022-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220803_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Tag'),
        ),
    ]
