# Generated by Django 3.0.4 on 2022-08-11 14:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220807_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='code_here',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
