# Generated by Django 3.0.4 on 2022-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220811_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.Tag'),
        ),
    ]
